### ISSUE TITLE
Cant get images with the last version.

### ISSUE THREAD

**Issue by Leinad4Mind** [jasonmayes/Twitter-Post-Fetcher#160]

**Comment by bhovens** [comment]
I assume I experience the same issue:

since approximately 1 day, images embedded in tweets (pics.twitter.com/[…] links) are no longer displayed in the embedded stream/tweet. Tested this with multiple browsers for Mac and PC. The profile picture of the Twitter user is visible. The stream is embedded on a webpage managed by [stacey](http://www.staceyapp.com/).

**Comment by jasonmayes** [comment]
This is a duplicate of another thread for which someone has suggested a patch. Waiting to hear back about some questions around their code.

**Comment by Leinad4Mind** [comment]
Can you link to the "other thread". Thank you!

**Comment by jasonmayes** [comment]
https://github.com/jasonmayes/Twitter-Post-Fetcher/issues/126

This is now fixed in 17.0.3 just published it.
