### ISSUE TITLE
Disabling picture requests ?

### ISSUE THREAD

**Issue by joDelicious** [jasonmayes/Twitter-Post-Fetcher#30]
Hi Jason, 

Thanx for sharing your work.

... you got it :   I don't need any images from twitter on my website, yet there are a lot of requests going on.  Is there a way i can ask to bypass any image requests ?

Cheerz !

Johan

**Comment by dvorapa** [comment]
:+1:

**Comment by jasonmayes** [comment]
Not without re-writing the Twitter Fetcher. The problem here lies in that some browsers will fetch images when I am constructing a variable in memory which contains HTMLElements. For example if I have:

var x = document.createElement('div');

x.innerHTML = 'some html string';

Now, even though I have not actually added this div to the DOM yet, it seems browsers will parse its children and prefetch the images.

The reason I construct a temporary DOM is for ease of parsing HTML from twitter, without actually using the Twitter widget (as we dont want that, but we do want to get at it's data).

The only way around this would be to manually parse the raw HTML string (which is subject to change too from time to time) which means any method used must be very robust and work in all the browsers I support currently...

I hope that helps explain why it is happening at least.

The reason why I have not spent time re-writing this solution is because I intended the Twitter Fetcher to be a temporary fix for people who did not have time to implement the new API just yet. With time, it is understandable that most people will use the new official API, so I feel it is not quite worth spending days of development on as most people actually want the images, and if not, the performance is no worse than just including the regular twitter widget on your page anyhow.

**Comment by joDelicious** [comment]
Ok, i understand.  Thank you.
