### ISSUE TITLE
Clearer class structure for styling?

### ISSUE THREAD

**Issue by baloneysandwiches** [jasonmayes/Twitter-Post-Fetcher#31]
Hey Jason, This is awesome. After fiddling with OAuth for longer than I care to admit I stumbled onto this. Bravo, sir!

One quibble I have has to do with how classes are named. I think it should be configurable in a BEM-style structure, to avoid class name collisions and make the component structure crystal clear. If you're using SCSS, this also makes styling a breeze.

Please look at my fork:

https://github.com/jasonmayes/Twitter-Post-Fetcher/compare/master...baloneysandwiches:master

I'm happy to revise and/or submit this a PR if this is something you are interested in incorporating.

**Comment by jasonmayes** [comment]
Hello! Thanks for the kind words. :-)

So just for background, the classes that are spat out for the tweets themselves are straight from the twitter widget (which I do not directly control - yes I could theoretically re-write them, but they themselves are subject to change which is why I did not go down that route. It is down to twitter if they keep them like that or not and didnt want to have code that relied on that making it potentially fragile).

With regards my example classes I provide in demos - sure these can certainly be changed as you have done.

With regards merging:

SCSS - I will have to decline. Whilst more experienced developers can appreciate the niceties that come with this, 90% of the people currently using Twitter Fetcher are new to web programming (I get an email almost every week asking how to run the current version even without the SCSS). I strongly believe this will be too complex for the target audience in this case so would like to keep it regular CSS which anyone can modify without having to "compile" so to speak (and therefore need some extra knowledge about npm / command line etc too).

I think for now it is best to keep the SCSS version you have made in its forked state. If people are looking for SCSS / BEM version I am  happy to point them there. Or maybe we could take the BEM part of this and merge that only (assuming comments provided on the BEM notation for anyone not familiar with it). My main point is that I want to keep the code as simple as possible so people can hack with it as they wish (even with little experience).

**Comment by baloneysandwiches** [comment]
Thanks, I totally understand and share your concerns about keeping it simple.

The thing is, most of the current class naming structure is actually coming from your markup strings, not from Twitter. It's a mix, but the script is classing the the high level parent containers directly. I totally get that this is all very fragile in a sense, and subject to breakage if and when Twitter changes things. But the way it's currently written doesn't avoid that reality either. That's true either way.

Would it address your concerns if we were to set `baseClassName` in my fork to default to something like "twt", and then compile a css file based on that for inclusion in the repo? That way, novice users could just grab the CSS file, and edit it as-is. I could put a warning at the top of the SCSS file saying "Hey you, if you don't know what SCSS is, please just edit the CSS file!"

I say this because I really think both novice and advanced users would benefit from this repo including a more-defined default stylesheet. The absence of class-hooks on the various elements was a real issue for me the moment I had to start writing CSS for this.
